package com.school.mapper;

import com.school.model.SignRecord;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

public interface SignRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_record
     *
     * @mbggenerated Fri Dec 27 23:41:01 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_record
     *
     * @mbggenerated Fri Dec 27 23:41:01 CST 2019
     */
    int insert(SignRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_record
     *
     * @mbggenerated Fri Dec 27 23:41:01 CST 2019
     */
    SignRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_record
     *
     * @mbggenerated Fri Dec 27 23:41:01 CST 2019
     */
    List<SignRecord> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_record
     *
     * @mbggenerated Fri Dec 27 23:41:01 CST 2019
     */
    int updateByPrimaryKey(SignRecord record);

    List<SignRecord> findStudentSignRecord(Long studentId);

    SignRecord findStudentSignRecordByDate(@Param("studentId") Long studentId, @Param("date") Date date);
}