package com.school.mapper;

import com.school.model.SignRecord;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

public interface SignRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_record
     *
     * @mbggenerated Fri Dec 27 23:41:01 CST 2019
     *
     * 根据id删除
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_record
     *
     * @mbggenerated Fri Dec 27 23:41:01 CST 2019
     *
     * 插入
     */
    int insert(SignRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_record
     *
     * @mbggenerated Fri Dec 27 23:41:01 CST 2019、
     *  根据id获取信息
     */
    SignRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_record
     *
     * @mbggenerated Fri Dec 27 23:41:01 CST 2019
     * 获取全部信息
     */
    List<SignRecord> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_record
     *
     * @mbggenerated Fri Dec 27 23:41:01 CST 2019
     * 根据id更新西悉尼
     */
    int updateByPrimaryKey(SignRecord record);

    /**
     * 根据学生id查询所有签到信息
     * @param studentId
     * @return
     */
    List<SignRecord> findStudentSignRecord(Long studentId);

    /**
     * 根据学号 姓名 查看签到信息
     * @param studentId
     * @param date
     * @return
     */
    SignRecord findStudentSignRecordByDate(@Param("studentId") Long studentId, @Param("date") Date date);
}