package com.school.model;

import java.util.Date;

public class SignRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_record.id
     *
     * @mbggenerated Fri Dec 27 23:41:01 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_record.student_id
     *
     * @mbggenerated Fri Dec 27 23:41:01 CST 2019
     */
    private Long studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_record.date
     *
     * @mbggenerated Fri Dec 27 23:41:01 CST 2019
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_record.ip
     *
     * @mbggenerated Fri Dec 27 23:41:01 CST 2019
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_record.sign_time
     *
     * @mbggenerated Fri Dec 27 23:41:01 CST 2019
     */
    private Date signTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_record.id
     *
     * @return the value of sign_record.id
     *
     * @mbggenerated Fri Dec 27 23:41:01 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_record.id
     *
     * @param id the value for sign_record.id
     *
     * @mbggenerated Fri Dec 27 23:41:01 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_record.student_id
     *
     * @return the value of sign_record.student_id
     *
     * @mbggenerated Fri Dec 27 23:41:01 CST 2019
     */
    public Long getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_record.student_id
     *
     * @param studentId the value for sign_record.student_id
     *
     * @mbggenerated Fri Dec 27 23:41:01 CST 2019
     */
    public void setStudentId(Long studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_record.date
     *
     * @return the value of sign_record.date
     *
     * @mbggenerated Fri Dec 27 23:41:01 CST 2019
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_record.date
     *
     * @param date the value for sign_record.date
     *
     * @mbggenerated Fri Dec 27 23:41:01 CST 2019
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_record.ip
     *
     * @return the value of sign_record.ip
     *
     * @mbggenerated Fri Dec 27 23:41:01 CST 2019
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_record.ip
     *
     * @param ip the value for sign_record.ip
     *
     * @mbggenerated Fri Dec 27 23:41:01 CST 2019
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_record.sign_time
     *
     * @return the value of sign_record.sign_time
     *
     * @mbggenerated Fri Dec 27 23:41:01 CST 2019
     */
    public Date getSignTime() {
        return signTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_record.sign_time
     *
     * @param signTime the value for sign_record.sign_time
     *
     * @mbggenerated Fri Dec 27 23:41:01 CST 2019
     */
    public void setSignTime(Date signTime) {
        this.signTime = signTime;
    }
}